# redis 설정.
redis:
    hosts: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
    password:
    ssl: false
    timeout: 1


# coroutine dispatcher thread-pool 설정.
coroutine:
  io:
    common: 64
    db: 256
    redis: 256
    logging: 64
    async: 256
    http: 256

# ktor http client 설정.
ktor:
  client:
    engine:
      thread-count: 4
      max-connection-count: 10000
      request-timeout: 1000
    endpoint:
      max-connections-per-route: 100
      pipeline-max-size: 20
      keep-alive-time: 1000
      connection-attempts: 5
      connection-timeout: 500
