database:
  redis:
    hosts: 183.110.51.54,183.110.51.43,183.110.51.186
    port: 7001
    timeout: 1
    pool:
      maxTotal: 10
      maxIdle: 10
      minIdle: 10
  dynamodb:
    endpoint: https://amazon.com
    region: ABCDEF

ktor:
  client:
    engine:
      threadCount: 4
      maxConnectionsCount: 10000    # .net 의 maxConnection 과 비슷
      requestTimeout: 1000          # request timeout
    endpoint:
      maxConnectionsPerRoute: 100   # 각 호스트 단위의 최대 연결 수 (default: 100)
      pipelineMaxSize: 20           # httpPipeLine 을 기다리지 않고 단일 연결을 통해 보낼 최대 요청 갯수(default 20)
      keepAliveTime: 5000           # keep-alive 유지시간 (MilliSeconds)
      connectTimeout: 1000          # ConnectionTimeout (Milliseconds)
      connectAttempts: 5            # 재 연결 시도 횟수

coroutine:
  limitParallelism:
    db: 256
    dynamo: 256
    redis: 256
    log: 256